### ISSUE TITLE
Refactoring TODO for Videos

### ISSUE THREAD

**Issue by leggsimon** [Financial-Times/next-graphql-api#185]
### Start looking to deprecate the older Video Type:

- [ ] Expose [`brand`](https://github.com/Financial-Times/next-graphql-api/pull/181/files#diff-a238dd322ae75ca924414356454f42b7R37) and [`duration`](https://github.com/Financial-Times/next-graphql-api/pull/181/files#diff-a238dd322ae75ca924414356454f42b7R51) fields from "media video" to `VideoContent`. This will mean importing `backend-adapters/video.js` in `types/content.js`

- [ ] Expose duration as seconds & move duration formatting logic to n-card (or wherever it is used)

- [ ] Move placeholder image to `VideoContent`. If it comes from CAPI all good, if not, get it from brightcove.

In [`next-front-page`](https://github.com/Financial-Times/next-front-page):

- [ ] change front-page query to query VideoContent instead of media video [here](https://github.com/Financial-Times/next-front-page/blob/75a43681c83835aa61d0046ed5f6df4f9d2002f9/config/queries.js#L241)

💭 
- If editorial are going to create a list for the front-page video element we should use that instead of using brightcove playlists?
